//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class generalinfo
    {
        public int idgeneralInfo { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public int product_idproduct { get; set; }
        public string type { get; set; }
    }
}
